### PR TITLE
feat: Set value overrides within cloudquery config

### PR DESCRIPTION
**Pull request by lm-t**
I'm adding ability to set value overrides e.g `--set` on the cloudquery config section. This will allow setting value overrides on sensitive values such as the database password.

### CODE REVIEW

**Review by yevgenypats — APPROVED** [review]

**Comment by erezrokah** [comment]
Hi @lm-t and sorry for the late follow up. We were in the process of migrating this repo to [CloudQuery v1](https://www.cloudquery.io/blog/cloudquery-v1-release).

With that change, I'm not sure this PR is needed anymore, as one can set the DB password by setting an environment variable, for example:
```
helm install cloudquery ./charts/cloudquery/ -f ./charts/cloudquery/values.yaml \
    # Assuming CQ_DSN is set in the current shell
    --set envRenderSecret.CQ_DSN=$CQ_DSN
```
and given the default configuration:
https://github.com/cloudquery/helm-charts/blob/3623f27ba68b039589b1f914b3c973fea56b56eb/charts/cloudquery/values.yaml#L81

Will that work for your use case? And if not can you share it and what capability we're missing?

**Comment by erezrokah** [comment]
Going to close as stale per my last comment. @lm-t if still relevant for you please comment and we can bring this up to speed

**Comment by lm-t** [comment]
@erezrokah Yes, this use case works. Sorry for the delay I had to redesign how it was configured because of the new version configuration format.

**Comment by erezrokah** [comment]
Thanks for following up @lm-t and for the contribution! Sorry it took us such a long time to respond.

**Pull request closed without merging**
